version: "{build}"

os:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

platform:
  - x64

before_build: 
  - cmd: cd C:\projects\Box2D-cocos2d-x\Box2D      
  - cmake -H. -BBuild -A%PLATFORM%

build:    
  project: c:\projects\Box2D-cocos2d-x\Box2D\build\Box2D-cocos2d-x.sln
                 
test_script:
  - cd Build
